export const replacements = {
  'á': 'a',
  'é': 'e',
  'ó': 'o',
  'ö': 'o',
  'ú': 'u',
  'ý': 'y',
  'æ': 'ae',
  'ð': 'd',
  'þ': 'th',
  // 'þ': 'p',
  'y': 'i',
  'i': 'y',
  // 'ý': 'í',
  'í': 'ý',
  'ang': 'áng',
  'eng': 'eing',
  // 'eng': 'eyng',
  'ing': 'íng',
  // 'ing': 'ýng',
  'ung': 'úng',
  'yng': 'íng',
  // 'yng': 'ýng',
  'öng': 'aung',
  'ank': 'ánk',
  'enk': 'eink',
  // 'enk': 'eynk',
  'ink': 'ínk',
  // 'ink': 'ýnk',
  'unk': 'únk',
  'ynk': 'ínk',
  // 'ynk': 'ýnk',
  'önk': 'aunk',
  'agi': 'ægi',
  'egi': 'eigi',
  // 'egi': 'eygi',
  'igi': 'ígi',
  // 'igi': 'ýgi',
  'ogi': 'oji',
  'ugi': 'uji',
  'ygi': 'yji',
  'ögi': 'augi',
  'f': 'v',
  'hv': 'kv',
  'll': 'dl',
  'nn': 'dn',
  'fnd': 'md',
  // 'fnd': 'mt',
  'fl': 'bl',
  'fn': 'bn',
  'rl': 'rdl',
  'rn': 'rdn',
  'sl': 'sdl',
  'sn': 'sdn',
  't': 'gt',
  // 't': 'kt',
  'ófi': 'ói',
  'ófa': 'óa',
  'úfa': 'úa',
  'nl': 'ngl',
  'gld': 'lgd',
  'rnd': 'nd',
  'rst': 'st',
  // 'þ': 'ð',
  'x': 'gs',
  // 'x': 'ks',
  'gs': 'x',
  'ks': 'x',
}
